### ISSUE TITLE
how to fix 

### ISSUE THREAD

**Issue by CuneoTop** [duongthu123/Discord-ddos-bot#1]
[database] database check...
/home/kali/Discord-ddos-bot/node_modules/@discordjs/ws/dist/index.js:1132
          error: new Error("Used disallowed intents")
                 ^

Error: Used disallowed intents
    at WebSocketShard.onClose (/home/kali/Discord-ddos-bot/node_modules/@discordjs/ws/dist/index.js:1132:18)
    at connection.onclose (/home/kali/Discord-ddos-bot/node_modules/@discordjs/ws/dist/index.js:676:17)
    at callListener (/home/kali/Discord-ddos-bot/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/home/kali/Discord-ddos-bot/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:517:28)
    at WebSocket.emitClose (/home/kali/Discord-ddos-bot/node_modules/ws/lib/websocket.js:260:10)
    at TLSSocket.socketOnClose (/home/kali/Discord-ddos-bot/node_modules/ws/lib/websocket.js:1272:15)
    at TLSSocket.emit (node:events:529:35)
    at node:net:351:12
    at TCP.done (node:_tls_wrap:657:7)

**Comment by CuneoTop** [comment]
already fix it but the slash commands isnt showing
